### ISSUE TITLE
Special Project Supplies

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#102]
Work with Joanna to purchase pink bins specifically for special project supplies.

**Comment by AlexandraDowlin-NOAA** [comment]
@bethanyriggle is it possible to update the deadline for this task to April 12th. That is the date we are telling PIs to get their supplies to us by.
Let me know if that is okay or not.

**Comment by bethanyriggle** [comment]
@AlexandraDowlin-NOAA yup! No problem!

**Comment by AlexandraDowlin-NOAA** [comment]
April 12th is the deadline for project supplies. What do you think will be helpful for us to keep track of scientific projects and their supplies? excel sheet, binder, print outs, xyz, open to your thoughts. I want to get this defined before the madness of everyone shipping stuff. Thanks!

**Comment by AlexandraDowlin-NOAA** [comment]
Most project supplies have made it to Seattle. I may use this Friday 4/19 to create a proper tracking spreadsheet. I will share when able. With us rounding the corner, it seems that finding totes for project supplies for each vessel is our next step. And hot pink duct tape (:
