### ISSUE TITLE
Review and add survey standards for haul, length, and specimen

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#107]
[Conversations](https://github.com/afsc-gap-products/GOA-Survey-Planning/issues/37) from last year.

Megsie addition:
Heather instructions for changing standards in GIDES are [here](https://docs.google.com/document/d/17tRWrwY7hC-xSUxvTeom8EX4HhF-cKsE/edit). Haul standards cannot be changed and saved in GIDES; it is a "whole thing" Ned is trying to get changed. 

**When these instructions get copied for future years: duplicate even years for AI survey standards and odd years for GOA survey standards.**

Task list is the same (I think) as last year:
 
- [x] Haul: Standards should be the same (import from AI 2022)
- [x]  Specimen: Need to confirm oto sampling plan and edit oto collection standards for species based on what Zack gets from the SA people. 
- [x]  Length: I think these will remain the same too. (import from AI 2022)

**Comment by MargaretSiple-NOAA** [comment]
Hi Ned and Sarah! Y'all wanna set up some time to do this? Ned, I'm not aware of any haul or length standards that need to change, so I think we're just waiting for the otolith negotiation team to give us oto guidance. Are my assumptions correct?

**Comment by SarahFriedman-NOAA** [comment]
Happy to look into this tomorrow, otherwise I will be on leave for the next couple of weeks.

**Comment by MargaretSiple-NOAA** [comment]
Eek! Glad I caught you in time. Yeah let's chat about it tomorrow. If we're lucky Ned will tell us haul and length are good 2 go and then we can just talk about the specimen standards.

**Comment by SarahFriedman-NOAA** [comment]
General, length, and specimen standards have been copied from the GOA 2023 survey. For future reference, the documentation for this process is [here](https://docs.google.com/document/d/17tRWrwY7hC-xSUxvTeom8EX4HhF-cKsE/edit#heading=h.z0zg7nlvazsm). 

@zoyafuso-NOAA do you have any indication of the new specimen standards for this year? I am assuming changes will need to be made. If nothing else it currently has the GOA species list and this will need to be altered for an AI year.

**Comment by MargaretSiple-NOAA** [comment]
I was wrong in my initial text and said to copy length and specimen standards from GOA 2023 and it should have been AI 2022! But I have now fixed it. They're now duplicated from the last AI survey.

All we need to do now is sort out whether we need to change any of the length weight params in the LW standards, and update specimen standards based on what Zack says.

**Comment by zoyafuso-NOAA** [comment]
I am very close to finishing the otolith negotiations with an internal GAP deadline of Feb 19th (Megsie: I lost the Atka fight, we're doing Up to 10...) I should have this done by next Tuesday's team meeting.

**Comment by Ned-Laman-NOAA** [comment]
Tiny note. If the text for this action is going to live on into the future, it could say duplicate AI for even years and Gulf for odd years!

**Comment by MargaretSiple-NOAA** [comment]
> Tiny note. If the text for this action is going to live on into the future, it could say duplicate AI for even years and Gulf for odd years!

This was 110% my fault, I wrote it down wrong in my edits of the task description! It is now fixed in word and deed and we never have to think about it again!

And thank you Zack re: the otolith negotiations. I'll check back after Feb 19.  Sad about the Atka but would still rather do 10 of those than some of the giant tough rockfishes!

**Comment by MargaretSiple-NOAA** [comment]
I have updated the length standards for AI 2024 according to the updated LW params that Cecilia updated. These are the same parameter values that are in `RACE_DATA.LENGTH_WEIGHT_PARAMETERS`. So I think we can consider the length standards updated.

Two things I learned through my efforts and communications on this task this year:
1) The parameter values we have in Survey Standards for Length in GIDES don't automatically update from RACE_DATA. Ned and I both note that it would be nice if this updated automatically. 
2) I noticed some species in the standards that weren't suggested updates this year (e.g., grenadier), that are different between the `RACE_DATA` length weight parameter table and the values in GIDES. I summarized them in a csv (linked below). I don't think this is a huge deal, we should just keep an eye on it.

[gides_comparison_AI2024.csv](https://github.com/afsc-gap-products/GOA-AI-Survey-Planning/files/14366729/gides_comparison_AI2024.csv)

**Comment by MargaretSiple-NOAA** [comment]
Oto list is here: https://docs.google.com/spreadsheets/d/1n0elwv6bUoSgCCCLPtEUZF6XFa8FMlpbH7w797HoQRs/edit#gid=1924553237

The random ones can be added now (because they'll be for both boats) and other ones will be assigned to a vessel during a special allocation meeting that hasn't happened yet. 

I still need to update the random collections in GIDES standards, just a little behind the times at the moment.

**Comment by MargaretSiple-NOAA** [comment]
Specimen standards have now been updated according to the [oto collection requests](https://docs.google.com/spreadsheets/d/1n0elwv6bUoSgCCCLPtEUZF6XFa8FMlpbH7w797HoQRs/edit#gid=1924553237) (thanks @zoyafuso-NOAA !). All are random collections so are on both boats. There is an ongoing discussion with Chris A about whether GIDES automatically updates from RACE_DATA (I am >90% sure it doesn't) but that doesn't need to happen on this task thread! This task is now complete.

**Comment by Ned-Laman-NOAA** [comment]
Here's the dealio; there's always a wrinkle. IPHC isn't sending a sampler out this year. They've requested otolith collections of us through the scientific collection request process. The collection rubric is still being negotiated but it will be random and on both vessels. I'd like to have the halibut collection treated as a CORE collection for purposes of the otolith placards and specimen standards so that we can use our specimen tablets and integrate the halibut collection into our standard otolith extraction activities. Ping me if you have questions.

**Comment by MargaretSiple-NOAA** [comment]
@Ned-Laman-NOAA When you get the chance, can you forward me the collections request so I know what sample size/details to put in the specimen standards?

**Comment by Ned-Laman-NOAA** [comment]
The collection request is being negotiated now so I don't have the final yet. I'm bound to forget to put it here when IPHC finally responds, but will do my best to remember!

**Comment by MargaretSiple-NOAA** [comment]
I have updated the specimen standards for AI 2024 to include P. halibut, all up to 6, 6 over 6.

**Comment by Ned-Laman-NOAA** [comment]
Sweet! Thank you.
