### ISSUE TITLE
Environmental Compliance

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#115]
Standing agreement at the Center level. Not something we directly request or generate, but we need to be aware of this.

**Comment by Ned-Laman-NOAA** [comment]
This agreement is initiated and maintained by Rebecca Reuter out of the Director's Office

**Comment by Ned-Laman-NOAA** [comment]
This is an AFSC-wide permit maintained out of the Center Director's office; currently by Rebecca Reuter.
