### ISSUE TITLE
Print Physical Charts

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#117]
Once all elements have been added to electronic station charts, the following steps need to be made:

- [x] Send PDF's of each chart to Paul Irvin in the printing office, so he can print drafts of each.

- [x] Hang the drafts in the hallway for staff members to look at and add notes to things that need editing.

- [ ] Update anything you have been given feedback for on the electronic charts.

- [ ] Send final PDF's to Paul Irvin, and charts need to be printed with these dimensions: 36 X 48 inches.

- [ ] Ensure that each vessel has one of each chart (1-4), then put in labeled tubes to be packed in the vans before doors closed.

**Comment by Ned-Laman-NOAA** [comment]
This is the printing of the Final Draft - partial drafts should be printed sooner for review
