### ISSUE TITLE
Putting together document

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#119]
Make sure there is time to review document prior to *insert date here*

**Comment by Ned-Laman-NOAA** [comment]
Can you link the document here so we're all pointed at the right place?

**Comment by Conrathcl** [comment]
Apologies - I seem to have turned off notifications for the survey assignments, but still left on the ones I don't want to get:)

The doc is here:  G: Aleutian/AI 2024/Ops Plan.  I don't know how to link that location here - and I think best to not have it as a google doc while there is a copy in the g-drive.  If we want to switch to a google doc, I will take the one out of the g-drive. 

The updated to do list:
Sarah will check the min. species ID this week.
Check to see if length-frequency table is still good
Update contacts for vessels
Update survey personnel table closer to time - it is relatively up to date now.

**Comment by Ned-Laman-NOAA** [comment]
There are no changes to the length subsample numbers table.

The FTP password has changed but hasn't been communicated directly to me yet. I'd assumed it would show up somewhere in the RACE Survey App but haven't found it yet. Perhaps check with Sarah or I'm pretty sure Sean Rohan knows it.

**Comment by Ned-Laman-NOAA** [comment]
Housekeeping.
I now have the FTP password if you still need it let me know.
I've finished edits and suggested revisions to the draft.
One big thing I didn't "do" but could be done is to create an appendix of Sean Rooney's updated chems language and then reference it in text for everything from our sections on Safety and Procedures to the using the same addendum for the Stomach Lab collection request.
From my point of view, this document is pretty much ready once any edits or comments have been addressed and Christina is satisfied.

**Comment by Conrathcl** [comment]
Hi Ned and all,
I dropped the ball on this but will pick it back up on Tuesday with the aim of finishing it up next week.
If you have the FTP password that would be great.  
I'll work on getting the special projects in next week.  
Apologies to Sean as I haven't had a chance to review the chemical/safety changes.  It sounds like he is willing to incorporate them directly into the text and I think that is the best path forward.  I'll review on Tuesday morning.  
Hopefully this delay will give us the opportunity to get the OSI job numbers in as well -another project we can tackle next week.
Thanks -

**Comment by Conrathcl** [comment]
I took a quick look at Ned's edits and a couple of things jumped out:

1) 'Add Marport workaround instructions and path to code for those instances when Wheelhouse won’t download the .marp file'

Is this written up somewhere?  Or who is best to ask to write it up?  

2) Volumetric language (and virtually all the language in the document) came from the 2023 Ops plan for the GOA. I tried to only keep text that seemed specific to the Aleutians survey. 

Sausage method - I'm not sure I know how to do this.  I did participate in this one time but Bill did most of the heavy lifting (and it was 10?ish years ago).  Calculating the volume is probably easy enough using the calculations on theback of the catch form. Not sure how we get the random density sample?  And from there I guess the rest is the same.

**Comment by Ned-Laman-NOAA** [comment]
I recommend Megsie or Bethany as the two people most recently familiar with the Alison workaround to the .marp loading tool.

I recommend Pearl as the expert on the sausage method since it's a common tool used by observers and she seems to be the most well-versed in it's use.

I think we need to be considering how the "back of the catch form" becomes a more readily available reference either in the Ops Man, the Survey App, or both...though you ultimately need it in hand on deck when you're doing this method

**Comment by Conrathcl** [comment]
Getting close:  special projects are in, Megsie provided some text on the work around, Pearl provided some text on the volumetric part 1b, as well as a diagram of shapes/volumes to include in the Ops manual as an appendix, so we have an alternative to the catch form.  I'll clean it up a little on Thursday. If there is a new map that would be helpful, but if not I can put something together.

**Comment by Conrathcl** [comment]
Trying and failing to find updated vessel contacts.  I asked Jerry but haven't heard back.  Is this something that exists already somewhere?  

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/CHRIST~1.CON/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<title>RACE DIVISION FIELD OPERATIONS EMERGENCY* NOTIFICATION PLAN</title>

<link rel=themeData
href="file:///C:/Users/CHRIST~1.CON/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/CHRIST~1.CON/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link="#800040" vlink="#954F72" style='tab-interval:.5in'>


<h1><a name="_Toc166134552"></a><a name="_Toc356887900"></a><a
name="_Toc260895765"><span style='mso-bookmark:_Toc356887900'><span
style='mso-bookmark:_Toc166134552'><b style='mso-bidi-font-weight:normal'><font
size=4 color=black face="Times New Roman"><span lang=X-NONE style='font-size:
15.0pt;line-height:150%'><span style='mso-bidi-font-size:10.0pt;line-height:
150%'>Appendix </span></span></font></b></span></span></a><span
style='mso-bookmark:_Toc260895765'><span style='mso-bookmark:_Toc356887900'><span
style='mso-bookmark:_Toc166134552'><span style='mso-ansi-language:EN-US'>D</span><span
lang=X-NONE>: Communications</span></span></span></span><span lang=X-NONE><o:p></o:p></span></h1>

<p class=MsoNormal><font size=3 face="Times New Roman"><span style='font-size:
12.0pt'>Inmarsat numbers, call signs, and operating periods for chartered
vessels<o:p></o:p></span></font></p>

<p class=MsoNormal><font size=3 face="Times New Roman"><span style='font-size:
12.0pt'><o:p>&nbsp;</o:p></span></font></p>


Vessel | Call   Sign | Survey   Dates | Survey
-- | -- | -- | --
F/V Alaska Provider | WDG 2215 | 5   June – 03 August | AI   Bottom Trawl Survey
F/V Ocean   Explorer | WCZ   9006 | 4   June – 02 August | AI   Bottom Trawl Survey



<p class=MsoNormal style='mso-pagination:none'><font size=3
face="Times New Roman"><span style='font-size:12.0pt;layout-grid-mode:line'><o:p>&nbsp;</o:p></span></font></p>

<p class=Level1 style='line-height:150%;mso-pagination:widow-orphan'><b><u><font
size=3 face="Times New Roman"><span style='font-size:12.0pt;mso-bidi-font-size:
12.0pt;line-height:150%;font-weight:bold'>Aleutian Island Vessel Office contacts<o:p></o:p></span></font></u></b></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
background:white'><b style='mso-bidi-font-weight:normal'><font size=3
color="#222222" face="Times New Roman"><span style='font-size:12.0pt;
color:#222222;font-weight:bold;mso-bidi-font-weight:normal'>Vessel: F/V Alaska
Provider</span></font></b><font color="#222222"><span style='color:#222222'><br>
Vessel Design: Pacific Trawler<br>
Call sign: WDG2215<br>
Vessel registration number:<br>
Home Port: Seattle<o:p></o:p></span></font></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
background:white'><font size=3 color="#222222" face="Times New Roman"><span
style='font-size:12.0pt;color:#222222'>Vessel Owner: US Seafoods<br>
Address: 1801 Fairview Avenue East, Suite 100; Seattle, WA 98102<br>
Phone: 206-763-3133<br>
Fax: 206-832-1695<br>
Contact: Matt Upton<br>
Alternate Contact:<br>
Captain: Loren Reynolds<o:p></o:p></span></font></p>

<p class=MsoNormal><font size=3 face="Times New Roman"><span style='font-size:
12.0pt'>On-board satellite telephone number (emergency): 206-701-7504<o:p></o:p></span></font></p>

<p class=MsoNormal><font size=3 face="Times New Roman"><span style='font-size:
12.0pt'>KVH VSAT# (wheelhouse), (galley) 206-701-7509<o:p></o:p></span></font></p>

<p class=MsoNormal><font size=3 face="Times New Roman"><span style='font-size:
12.0pt'>Cell phone number in Dutch Harbor: 907-359-1503<o:p></o:p></span></font></p>

<p class=MsoNormal><font size=3 face="Times New Roman"><span style='font-size:
12.0pt'>Vessel Email:<span style='mso-tab-count:1'> </span>Alaskaprovider@xgatemail.com<o:p></o:p></span></font></p>

<p class=MsoNormal style='mso-margin-top-alt:auto;mso-margin-bottom-alt:auto;
background:white'><b style='mso-bidi-font-weight:normal'><font size=3
color="#222222" face="Times New Roman"><span style='font-size:12.0pt;
color:#222222;font-weight:bold;mso-bidi-font-weight:normal'>Vessel: F/V Ocean
Explorer</span></font></b><font color="#222222"><span style='color:#222222'><br>
Vessel Design: Pacific Trawler<br>
Call sign: WCZ9006<br>
Vessel registration number: 678236<br>
Home Port: Seattle<o:p></o:p></span></font></p>

<p class=MsoNormal style='background:white'><font size=3 color="#222222"
face="Times New Roman"><span style='font-size:12.0pt;color:#222222'>Vessel
Owner: B &amp; N Fisheries<br>
Address: 303 NE Northlake Way, Seattle, WA 98105<br>
Phone: 206-553-9123; 206-783-1948<br>
Fax:<br>
Contact: Jerry Downing<br>
Alternate Contact: Cassie Owens<br>
Captain: Dan Carney<o:p></o:p></span></font></p>

<p class=MsoNormal style='background:white'><font size=3 color="#222222"
face="Times New Roman"><span style='font-size:12.0pt;color:#222222'><o:p>&nbsp;</o:p></span></font></p>

<p class=MsoNormal><font size=3 face="Times New Roman"><span style='font-size:
12.0pt'>On-board satellite telephone number: 206-480-1530 (wheelhouse) 1531
(galley)<o:p></o:p></span></font></p>

<p class=MsoNormal><font size=3 face="Times New Roman"><span style='font-size:
12.0pt'>Vessel Email: <a href="mailto:fvocean.explorer@gmail.com">fvocean.explorer@gmail.com</a><o:p></o:p></span></font></p>


</body>

</html>

**Comment by Conrathcl** [comment]
Barring any changes to the Vessel Contact information, I am done with the Ops Plan.  Last year Nate organized printing it.  I can discuss with him how to get this done when we are ready.

I also wanted to start a to do list for next year - additions/suggestions welcome:

1. Volumetric diagrams/pictures

**Comment by Conrathcl** [comment]
Ok - actually done this time. Updated the vessel contacts with info from Jerry.  Added in all the ancillary info from the special projects.  If anything else needs to be changed or added, let me know.
