### ISSUE TITLE
Allocation between boats

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#124]

**Comment by AlexandraDowlin-NOAA** [comment]
@bethanyriggle can you update this deadline to 3/15 ?

**Comment by Conrathcl** [comment]
Hi All - trying to check off some boxes.  

Are we good with the allocation proposed here?  [https://docs.google.com/spreadsheets/d/1znQi98uYY9AStXQABLlDAfOBU1osO5W8/edit?pli=1#gid=1004002797](url)

I think the big strategy question is put both DNA projects on one boat?  And balance by putting a couple of the larger projects on the other boat?   Or split?   I think most of the other decisions are straight forward.  

I think we are close to being ready to put the projects in the Ops Plan so it would be good to get this sorted.

Let me know what you think.

**Comment by Ned-Laman-NOAA** [comment]
Can you resend the link? That one doesn't seem to point to a doc.

**Comment by AlexandraDowlin-NOAA** [comment]
Vessels have been allocated. Here is the link: https://docs.google.com/spreadsheets/d/1pODOzo2yu8m_hjWq7iUsRJXrXofgeIfJkzuHum1xEwI/edit#gid=1068030
