### ISSUE TITLE
Travel Plans

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#126]
[Notes](https://docs.google.com/document/d/1eHNm6o2X5qSTR4C0kGTNr0sPqxz_ZfGNX53NLAsrMW4/edit?usp=drive_link), [draft emails](https://drive.google.com/drive/folders/1TRymLXTsJK3XnTOfO7686cKGXdpudH62), [staffing spreadsheets](https://docs.google.com/spreadsheets/d/1-uHp_eFK5YcGmHN5Q0JqTlqGby08ZyYTmiDvI-DdIXU/edit?usp=drive_link) all live [here](https://drive.google.com/drive/folders/1Zo3BSbX7DTCM0jOm5Ypg_HAZIfKIFGk8). 

Travel requests completed in [travel app](https://script.google.com/a/macros/noaa.gov/s/AKfycbwdQxgdDdWfoH_4bBK9xMfShQaqMPNogkTZx-VgC6tTx3aUMDogSxwEGWHWnAcZMSv4/exec):

- [x]  Travel requests for Leg 1
- [x]  Travel requests for Leg 2
- [x]  Travel requests for Leg 3

Send emails:

- [x] [Email 1](https://docs.google.com/document/d/1CoX5xOLoKe59xIatJF8vjVITJtrLYAUZ9HktQBaojX8/edit?usp=drive_link): Timekeeping info, E2 status, port guides, rain gear requests, training requirements (Sent March 12th)
- [x] [Email 2](https://docs.google.com/document/d/1kvD4JHscBwO95w8abLQHxdTuEe5ivPweyKiiYDRj33Y/edit): Send itineraries to us so we can put it on the Survey App
- [x] [Email 3](https://docs.google.com/document/d/1Kntq19sVSbu4SQx-6rb3KPyB-LvLCweE1vklftC_cDk/edit): work schedules, gmail codes, last minute stuff

**Comment by bethanyriggle** [comment]
Travel plans should be initiated by March 1, but finalized by mid-March for Leg 1 survey goers.

**Comment by SarahFriedman-NOAA** [comment]
There is a guide and resources I compiled for travel arrangements from last year [here](https://drive.google.com/drive/folders/1-Eo-wfM9Xp2GTvCZmBDe1soZY3n6azrd). Happy to answer any questions that arise!

**Comment by zoyafuso-NOAA** [comment]
Thank You @SarahFriedman-NOAA for the guide. I reorganized that folder so that the content Sarah shared is now in a subdirectory ("Gulf of Alaska/2023/"). I then copied those files into a new subdirectory called "Aleutians/2024/". Some files that are shared resources between the two surveys were moved to a folder called "Shared Resources". I haven't changed any of the content in the Aleutians/2024/ yet. 

Just a heads up, I will be on the MACE cruise March 3rd-22nd so I will have limited bandwidth (I assume) to handle tasks during then.

**Comment by AlexandraDowlin-NOAA** [comment]
@SarahFriedman-NOAA @bethanyriggle @zoyafuso-NOAA @Conrathcl 
Good morning Bethany and Sarah,
Zack, Christina and I are in charge of travel this year. We wanted to touch base 1. with where we are with the survey roster and 2. where we should be with the travel emails and requests. Bethany, if you could help confirm the survey roster and dates.Sarah, if you could help us understand where we should be with travel stuff. 
The three of us are traveling a bunch this month and are like ships passing in the night so any help on how we can be on top of things is greatly appreciated. 
Thanks!-Alex

**Comment by SarahFriedman-NOAA** [comment]
Hello! I think at this point in time it would be helpful to have TRs submitted for the leg 1 folks at least and perhaps send out [email #1](https://docs.google.com/document/d/1aFxZIiCBjif5bwO9RZZUUuSig_VMOLl9Zd51jju4_1A/edit). That way people have a bit more info and can get back to you if they want to extend their trips for personal travel. Summer travel in Alaska is busy so the sooner you can finalize travel plans and formally submit the requests to the travel arrangers the better.

**Comment by bethanyriggle** [comment]
Hello all! 

It has been determined that Leg 1 and 2 crews will be flying into Dutch Harbor the day before the leg starts, so they will also need accommodations at the Grand Aleutian for one night prior to embarking the vessel. 

Leg 1 OEX: Crews fly in on 06/03
Leg 1 AKP: Crews fly in on 06/04
Leg 2 OEX and AKP: Crews fly in on 06/26

Since Adak only has 2 flights a week, and the flights are more likely to make it in there as scheduled, the crews will be flying in the same day they embark for Leg 3.

Let @Ned-Laman-NOAA or myself know if you have any questions about this!

**Comment by zoyafuso-NOAA** [comment]
We're gonna call this one done. Great job everyone!
