### ISSUE TITLE
Posters for otoliths, special projects, and species codes

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#13]
Ensure that posters are previewed before they are sent to Paul Irvin in the printing office.

**Comment by AlexandraDowlin-NOAA** [comment]
We have finished the review process of the research projects and have assigned them to specific vessels. We will next send the project details to Emily.

**Comment by bethanyriggle** [comment]
@AlexandraDowlin-NOAA and @Conrathcl any updates on these? Is the deadline realistic for having these printed, or should we extend it?

**Comment by AlexandraDowlin-NOAA** [comment]
@bethanyriggle we have most things completed with a target of sending things to be printed by next week (4.18.23). Christina and I have special projects and otoliths covered. I am unsure who covers species codes.
