### ISSUE TITLE
Loading of apps on tablets

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#133]
In FY24 this task will begin in early March.

Megsie notes for this year and next:

Need to do before April training.
This task involves loading the .apk files onto all the tablets. Jerry can show us how to do this; in the past we have done it during the tablet training sessions too. We will need apk files for:

crab app
stomach app
length app
specimen app
catch app
We need to amke sure we have the most current version of each of them, then load them onto all the tablets going on the survey. All tablets should get all the apps. This task takes a while and helps to have helpers.

**Comment by SarahFriedman-NOAA** [comment]
This task is on hold currently as the specimen app needed some updates to the otolith collections and maturity tables. Unknown when it will be completed.
