### ISSUE TITLE
Create Station Allocation

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#137]

**Comment by zoyafuso-NOAA** [comment]
What is the difference between this task and #76 ?

**Comment by bethanyriggle** [comment]
@zoyafuso-NOAA this one is the actual generation of the station allocation, whereas #76 is updating the station allocation for Globe and ArcMap usage. They're basically the same thing, but different labels to ensure the necessary information gets provided for the Globe and ArcMap groups to include on their products!
