### ISSUE TITLE
Old tow paths/update with R output

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#3]
Both Globe and ArcMap files will need to be updated.

**Comment by coleary-noaa** [comment]
Sent updated towpaths, towstarts, midpoints shapefiles and survey grid csv from output of globe run to ArcMap team (Mark, Bethany, Alex)

**Comment by coleary-noaa** [comment]
Completed creation of necessary files:
- towpaths
- towstarts
- station locations
- survey grid

Extra files pulled in from updated 2022 shapefiles:
- SSL rookeries
- HAPC areas
- no transit zones
- otter areas
- NPRW zones

In process of training Susanne. 
Waiting for Gary to provide Globe computers to check all the files created and load to Globe computers.

updated Globe code to include all years when creating towpaths for ArcGIS and pushed to repo.

Remaining files to create when info received:
- crab pots
- buoys

**Comment by MargaretSiple-NOAA** [comment]
I haven't been watching these tasks until I started working on the Globe training slides, so I got here late! Did you use Sean's [navmaps package](https://github.com/sean-rohan-NOAA/navmaps) to do any of this? It should be able to produce all the files needed for Globe (though to be fair I personally have not tried it).  Sorry to pop up after you did this... I hope you used it! If you didn't, it should be helpful for the future.

**Comment by MarkZimmermann-NOAA** [comment]
Cecilia did the task of creating the tow paths for the 2021 data, using R,
I believe.
I'm working with Bethany and Alex to get them into ArcMap.

**Comment by coleary-noaa** [comment]
I did not use the new package because I was unaware of it until a few days ago. Created all the Globe files using the existing R files. Still waiting on Globe computers.

**Comment by MargaretSiple-NOAA** [comment]
Bummer-- that's my fault; I should have communicated about it more directly when we started the task list. In the future, that package should be able to produce files for both Globe and for TimeZero (if/when we use that), and OLEX.

**Comment by coleary-noaa** [comment]
one globe computer acquired! will start checking globe files ASAP

**Comment by coleary-noaa** [comment]
Globe files check out. Waiting on second Globe computer, and then will move on to 
- creating remaining files as information comes in
[ ] crab pots
[ ] buoys
[ ] special projects
[ ] Cecilia's drop-cam locations
- training Susanne when she returns from the field
- ensuring all files are on both computers
- testing navmaps package for file bridging as technology succession occurs
- return computers to Gary when done

**Comment by coleary-noaa** [comment]
Globe files check out. Acquired second computer.

- creating remaining files as information comes in
[ ] special projects
[ ] Cecilia's drop-cam locations

- ensuring all files are on both computers

- testing navmaps package for file bridging as technology succession occurs 
[ ] training Susanne on this

- return computers to Gary when done (early April)

**Comment by coleary-noaa** [comment]
Gary has asked for the Globe computers back by April 15.

**Comment by MarkZimmermann-NOAA** [comment]
Are you on track for getting everything done with the GLOBE computers, or
are you missing files? -Mark

**Comment by coleary-noaa** [comment]
everything is complete and checked! All globe files are on both computers. Holding on to them until next Wednesday in case any additional files pop up, the sandlace special project comes forward with a spatial file, and/or if Susanne becomes available to look at the computers next week for training.

**Comment by coleary-noaa** [comment]
All globe files loaded and checked, computers labelled GOA 2023. Gary is getting the computers from my office when he's ready. Globe navmaps test files also loaded for backup and comparison. Details of comparison will be put in issues of navmaps package.

**Comment by coleary-noaa** [comment]
All final globe files also in Files for boats as backup ( G:\GOA\GOA 2023\Files for boats\Globe )

**Comment by coleary-noaa** [comment]
Added in the navmaps package files for testing to the Files for boat

Timezero and olex test files found here: G:\GOA\GOA 2023\Files for boats\navmaps_test_files

Globe files found here: G:\GOA\GOA 2023\Files for boats\Globe\Lines\navmaps_test_files and G:\GOA\GOA 2023\Files for boats\Globe\Marks\navmaps_test_files
