### ISSUE TITLE
ID books

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#33]
Confirm that all ID guides are up to date and staged in building 8.

**Comment by SarahFriedman-NOAA** [comment]
Borrowed 1 coral guide; will need to return before shipping. Also, planning to print and laminate flow charts for deck guides.

**Comment by SarahFriedman-NOAA** [comment]
I plan to do this next week. Joanna has confirmed that the guides will still be unpacked then.

**Comment by SarahFriedman-NOAA** [comment]
Note for me for next year: print out laminated deck guide versions of min ID table
