### ISSUE TITLE
Pack/Load containers

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#34]
At-sea supply inventory will need to be conducted prior to the doors closing.

**Comment by joannamagner-noaa** [comment]
### Estimated dates, assuming May 15th start date
- **Containers @ WRC: 1st week of April, ~ April 4** 
    - _Gear staging location: TBD_
    - _Loading date(s): TBD_
    - _Sea bags due: TBD_
- **Doors closed: April 25**
    - Latest possible... May 2
- **Containers leave WRC: April 26**
    - Latest possible... May 3
- **Containers -> Dutch: depart Tacoma 04/28 -> arrive in Dutch 05/05**
    - Latest possible... depart Tacoma 05/05 -> arrive in Dutch 05/12

Exact dates still TBD. Will depending upon finalized start date for GOA survey and [Matson shipping schedule*](https://www.matson.com/fss/reports/alaska.pdf). 

_* Currently Matson's Alaska schedule is available only through March. Will need to check again in late February (or thereabouts) to determine the best sailing date._
