### ISSUE TITLE
Region SRP (protected spp consult first)

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#48]
Suzie Teerlink at Protected Species was the contact in 2022.

**Comment by smcdermo** [comment]
I just updated the scientific research plan and noted where we need to update.  I saved the plan here: [G:\GOA\GOA 2023\SRP](url)

**Comment by Ned-Laman-NOAA** [comment]
Received affirmative consultation from Protected Resources (Suzie Teerlink and Kim Raum-Suryan) on station conflicts with SSL NTZs on 3/29/23.
Submitted Research Plan to Rebecca Reuter for SRP application on 3/30/23
