### ISSUE TITLE
Special Projects

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#5]
Any Special Project that has specific areas for sampling will need to be included on the ArcMap and Globe charts.

**Comment by bethanyriggle** [comment]
For this year, there are 3 special projects that have specific sampling areas:

1. Wes Larson POP and Wes Larson Northern and Dusky rockfish: these have the same regions for collections. Last year Christina just provided the corner coordinates to make a box - there are three regions for his project.  

2. Bob McConnaughy project.  He has a bunch of locations that I think would muddy up the chart too much, but it might be nice to have a bounding box for where his project is occurring (mostly offshore of Kodiak).  He also provided a shapefile, so I'm wondering if we can just add that as a layer to the arcmap files?  
 
3. Sandlance project is around Unimak pass.


Christina has a google drive folder that has csv files for the Larson and McConnaughy projects, and a shape file that McConnaughy provided.

**Comment by coleary-noaa** [comment]
Here is the [google folder](https://drive.google.com/drive/folders/1CmVzCTL-d0d1BbIbAdRPK6OQYWYf2Ebi?usp=sharing)

**Comment by coleary-noaa** [comment]
Additional: 

4. O'Leary drop-cam station locations. File attached. Let me know if you have any issues @MarkZimmermann-NOAA @bethanyriggle @AlexandraDowlin-NOAA 

Formatting side note: In Globe, those locations are stars, and the UT stations are in reddish pink and T are in green.

[GOA_dropcam_stations_OLeary_2023.csv](https://github.com/afsc-gap-products/GOA-Survey-Planning/files/11092976/GOA_dropcam_stations_OLeary_2023.csv)
