### ISSUE TITLE
Travel plans

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#60]
The following need to be completed:

Travel requests drafted and sent to Ned:

- [x] Travel requests for Leg 1
- [x] Travel requests for Leg 2
- [ ] Travel requests for Leg 3
- [ ] Travel requests for Leg 4

Travel requests signed and sent to nmfs.afsc.race.admin@noaa.gov:

- [x] Leg 1
- [ ] Leg 2
- [ ] Leg 3
- [ ] Leg 4

Send emails:

- [x] Timekeeping info, E2 status, port guides, rain gear requests, training requirements
- [ ] Timekeeping, gmail authentication, health assessments (general COVID update)
- [ ] SIP guides
- [ ] Request travel itineraries from staff **and put on G Drive in Files for Boats**

Travel notes based on our meetings, that we will want for next year! (from Megsie)

- we arrange travel for all NOAA staff including people outside of RACE
- UW folks will need to determine who is paying for their survey travel (NOAA or UW, or a separate grant). If UW is paying NOAA back for travel, there is some additional paperwork. 
- If flights don't get into to SIP locations until later in the day, an extra scheduled day of SIP is needed (in 2023, this means 4 days instead of 3) 
- If using the online form for TR's, we need to submit one per traveler

**Comment by SarahFriedman-NOAA** [comment]
Can you (@bethanyriggle) assign me to this officially?

**Comment by bethanyriggle** [comment]
Travel plans should be initiated by March 1, but finalized by mid-March for Leg 1 survey goers.

**Comment by SarahFriedman-NOAA** [comment]
All leg 1 TRs submitted to the travel app! 

Note for future reference -- the budget code must be included for approval and TRs can not be edited once submitted. Budget code info from Michael Martin:

The accounting code for all things related to the GOA survey should be 30-61-0001-00-00-00-00 28LCB01 PC7. A quick tutorial on this accounting code for future reference:
30-61-0001-00-00-00-00 is RACE Division (30-61 is AFSC, 0001 is RACE). This is called the Org (Organization)  code
28LCB01 is the Project code. This is used for a lot of our survey activities
PC7 is the task code for the GOA survey (PC3 is AI for next year)

**Comment by SarahFriedman-NOAA** [comment]
All leg 2 TRs are submitted. I have also corresponded with all UW contractors about their travel plans.
