### ISSUE TITLE
Other(strata lines, sea lions, critical habitat, etc.)

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#79]
- [Stellar Sea Lion Critical Habitat data](https://www.fisheries.noaa.gov/resource/map/steller-sea-lion-western-dps-critical-habitat-map-and-gis-data) 
- [Humpback Whale Critical Habitat data](https://www.fisheries.noaa.gov/resource/map/humpback-whale-critical-habitat-maps-and-gis-data)
- Sea Otter Critical Habitat data
- North Pacific Right Whale Critical Habitat data
- Crab Pots
- Buoys

**Comment by bethanyriggle** [comment]
All layers besides crab pots will need to be generated by the end of January.

**Comment by AlexandraDowlin-NOAA** [comment]
Marked as done by @smcdermo. Closing the task.
