### ISSUE TITLE
Addition of all software on bridge computers, ready for cloning

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#82]
**This is for all bridge computers (_excludes METIS pc_)**

The software list includes our **data collection** software: 

- Wheelhouse/Calypso
- Scanmenu
- Hoboware
- Globe/TimeZero
- Portfolio 
- and more

As well **peripheral** softwares, like: 

- BVDRconverter
- SunriseSunset 
- Station Dropping Tool
- Basket Counting Spreadsheet
- WildLife Computers(light meter program)

**Note:** Usually the peripheral software stays on the survey computers from the previous years and gets cloned, so this task just entails making sure the right versions are there and that they work as expected.

**Comment by SarahFriedman-NOAA** [comment]
@zoyafuso-NOAA needs to be assigned to this task

**Comment by SarahFriedman-NOAA** [comment]
Adding a comprehensive list here of software that needs to be on each computer for future years. Italicized programs are carried over from past years and will likely just need to be checked for functionality, not necessarily updated. 

**Wheelhouse/Calypso**
- R >= 4.3.0
- Rtools 43
- R Studio (latest version)
- GAPsurvey R package 
- Adobe Acrobat Reader
- ArcMap (?)
- RACE Survey App
- _Scanmenu (not sure what this is)_
- _[HP1006 Printer drivers](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/HP1006_drivers)_
- _Wheelhouse/Calypso_
- _HOBOware_
- _BVDR Converter_
- _Wildlife Computers_
- _Hyperterm??_

**METIS**
- R >= 4.3.0
- Rtools 43
- R Studio (latest version)
- GAPsurvey R package (latest version when it's available)
- SBE Data Processing
- Seaterm
- Seasave
- Prolific serial driver
- Adobe Acrobat Reader
- RACE Survey App
- _Portfolio_
- _[HP1006 Printer drivers](https://github.com/orgs/afsc-gap-products/projects/4/files/Software/HP1006_drivers)_

**Marport** 
- _Light meters_
- _SiRFDemo_
- _CommandView_

**Globe**
- _Globe_
- _SiRFDemo_
- _Tides and Currents??_

**CTD laptops**
- R >= 4.3.0
- Rtools 43
- R Studio (latest version)
- GAPsurvey R package (latest version when it's available)
- SBE Data Processing
- Seaterm
- Seasave
- SeaView
- SBS Fathom
- Prolific serial driver
- RACE Survey App
- _Adobe acrobat reader_

**Comment by SarahFriedman-NOAA** [comment]
Sean mostly took the lead on this task. R was updated to version 3.6, which is due to Gary's specifications. I updated the survey app and will leave the testing to the testing team!
