### ISSUE TITLE
Posters for Otoliths, Special Projects, and Species Codes

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#88]
Ensure that all posters are previewed before sending to Paul Irvin or Rebecca White in the printing office.

**Comment by AlexandraDowlin-NOAA** [comment]
This task is still in progress. More appropriate deadline for sending printing inventory to Rebecca is 4/19.

**Comment by AlexandraDowlin-NOAA** [comment]
all things were printed, but I do need to go to the printing office to check that they are all good to go. If they are, we should be prepared to close this!
