### ISSUE TITLE
Inventory ES60 Calibration Kits

### ISSUE THREAD

**Issue by bethanyriggle** [afsc-gap-products/GOA-AI-Survey-Planning#89]
Inventory calibration kits, update the instructions, and forward to Survey App and Files For Boats teams.

**Comment by AlexandraDowlin-NOAA** [comment]
Just need to replace a roll of paper towels, some dish soap, copper spheres and print out new inventory list for each tote. Recommended to clean copper spheres again prior to shipping gear.

**Comment by AlexandraDowlin-NOAA** [comment]
to replace all needed supplies on 3/12, replace printed inventory list. 

- [ ] need to clean copper spheres prior to sending gear north
- [ ] ask MACE for proper handling and protocols

**Comment by AlexandraDowlin-NOAA** [comment]
need to replenish kits with needed inventory

**Comment by AlexandraDowlin-NOAA** [comment]
Finished! Both ES 60 kits are in building 8 are packed and finalized.
